/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sis3;

import java.io.FileOutputStream;
import java.sql.*; 
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import java.awt.Desktop;
import java.awt.HeadlessException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.io.InputStream;
import java.io.FileInputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import org.apache.commons.mail.DefaultAuthenticator;
import org.apache.commons.mail.Email;
import org.apache.commons.mail.EmailException;
import org.apache.commons.mail.SimpleEmail;

/**
 *
 * @author Apellido
 */
public class StudentInformation extends javax.swing.JFrame {
   DefaultTableModel dm;
   
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    boolean select = false;
    int stdntnmbr;
    File f;
    String s;
    /**
     * Creates new form Registration_form
     */
    public StudentInformation() {
        initComponents();
        conn = Connect.ConnectDb();
        Update_Table_StudentInfo();

    }
    
    private void filter(String query){
    dm = (DefaultTableModel) stud_info.getModel();
    TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(dm);
    stud_info.setRowSorter(tr);
    tr.setRowFilter(RowFilter.regexFilter(query));
    }
    
    private void Update_Table_StudentInfo(){
    try{
String sql = "select * from studentinfo";
pst=conn.prepareStatement(sql);
    rs=pst.executeQuery();
    stud_info.setModel(DbUtils.resultSetToTableModel(rs));
    }
catch(Exception e){
JOptionPane.showMessageDialog(null, e);
}finally{
    try{
        rs.close();
        pst.close();
        

      }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
      }
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stud_info = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        SaveButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        mi = new javax.swing.JTextField();
        fn = new javax.swing.JTextField();
        ln = new javax.swing.JTextField();
        sn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        free3 = new javax.swing.JTextField();
        elec4 = new javax.swing.JTextField();
        ps1 = new javax.swing.JTextField();
        it207 = new javax.swing.JTextField();
        ps2 = new javax.swing.JTextField();
        it206 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Information");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(704, 1088));
        setMinimumSize(new java.awt.Dimension(704, 1088));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_logo_copy.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 130, 95);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/REGpaint.png"))); // NOI18N
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(630, 0, 75, 110);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(null);

        stud_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        stud_info.setSelectionBackground(new java.awt.Color(153, 153, 153));
        stud_info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stud_infoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(stud_info);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 610, 402);

        jTabbedPane1.addTab("4Th Year - 1st Sem", jPanel2);

        jPanel3.setLayout(null);
        jTabbedPane1.addTab("4Th Year - 2nd Sem", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 640, 220));

        SaveButton.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        SaveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_save.png"))); // NOI18N
        SaveButton.setText("Save");
        SaveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveButton.setEnabled(false);
        SaveButton.setMargin(new java.awt.Insets(2, 7, 2, 14));
        SaveButton.setOpaque(false);
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 120, 40));

        UpdateButton.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        UpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_update.png"))); // NOI18N
        UpdateButton.setText("Update");
        UpdateButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UpdateButton.setEnabled(false);
        UpdateButton.setMargin(new java.awt.Insets(2, 7, 2, 14));
        UpdateButton.setMaximumSize(new java.awt.Dimension(73, 27));
        UpdateButton.setMinimumSize(new java.awt.Dimension(73, 27));
        UpdateButton.setPreferredSize(new java.awt.Dimension(73, 27));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(UpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 140, 40));

        jButton3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_delete.png"))); // NOI18N
        jButton3.setText("Delete");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setMargin(new java.awt.Insets(2, 7, 2, 14));
        jButton3.setMaximumSize(new java.awt.Dimension(73, 27));
        jButton3.setMinimumSize(new java.awt.Dimension(73, 27));
        jButton3.setPreferredSize(new java.awt.Dimension(73, 27));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 130, 40));

        jButton4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rsz_report.png"))); // NOI18N
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setLabel("Report");
        jButton4.setMargin(new java.awt.Insets(2, 7, 2, 14));
        jButton4.setMaximumSize(new java.awt.Dimension(73, 27));
        jButton4.setMinimumSize(new java.awt.Dimension(73, 27));
        jButton4.setPreferredSize(new java.awt.Dimension(73, 27));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 550, 120, 40));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PERSONAL INFORMATION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel4.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel10.setText("Password:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(10, 190, 100, 23);

        password.setEnabled(false);
        jPanel4.add(password);
        password.setBounds(150, 190, 380, 30);

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel9.setText("Age:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(10, 160, 32, 23);

        age.setEnabled(false);
        age.setMaximumSize(new java.awt.Dimension(100, 50));
        age.setMinimumSize(new java.awt.Dimension(100, 50));
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel4.add(age);
        age.setBounds(150, 160, 380, 30);

        mi.setEnabled(false);
        mi.setMaximumSize(new java.awt.Dimension(100, 50));
        mi.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel4.add(mi);
        mi.setBounds(150, 130, 380, 30);

        fn.setEnabled(false);
        fn.setMaximumSize(new java.awt.Dimension(100, 50));
        fn.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel4.add(fn);
        fn.setBounds(150, 100, 380, 30);

        ln.setEnabled(false);
        ln.setMaximumSize(new java.awt.Dimension(100, 50));
        ln.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel4.add(ln);
        ln.setBounds(150, 70, 380, 30);

        sn.setEnabled(false);
        sn.setMaximumSize(new java.awt.Dimension(100, 50));
        sn.setMinimumSize(new java.awt.Dimension(100, 50));
        jPanel4.add(sn);
        sn.setBounds(150, 40, 380, 30);

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Student Number:");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(10, 40, 124, 23);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Last Name:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(10, 70, 83, 23);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setText("First Name:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(10, 100, 84, 23);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setText("MI:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(10, 130, 25, 23);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel13.setText("Email:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 220, 100, 23);

        email.setEnabled(false);
        email.setMaximumSize(new java.awt.Dimension(100, 50));
        email.setMinimumSize(new java.awt.Dimension(100, 50));
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel4.add(email);
        email.setBounds(150, 220, 380, 30);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 540, 280));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GRADES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel5.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel12.setText("IT 209:");
        jPanel5.add(jLabel12);
        jLabel12.setBounds(10, 160, 100, 23);

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel14.setText("2nd Semester");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(330, 30, 100, 23);

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel15.setText("FREE 3:");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(10, 100, 100, 23);

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel16.setText("IT 207:");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(10, 130, 100, 23);

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel18.setText("ELEC 4:");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(10, 70, 100, 23);

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel19.setText("IT 206:");
        jPanel5.add(jLabel19);
        jLabel19.setBounds(270, 70, 100, 23);

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel20.setText("IT 209:");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(270, 100, 100, 23);

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel21.setText("1st Semester");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(50, 30, 100, 23);

        free3.setEnabled(false);
        free3.setMaximumSize(new java.awt.Dimension(100, 50));
        free3.setMinimumSize(new java.awt.Dimension(100, 50));
        free3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                free3ActionPerformed(evt);
            }
        });
        jPanel5.add(free3);
        free3.setBounds(150, 100, 40, 30);

        elec4.setEnabled(false);
        elec4.setMaximumSize(new java.awt.Dimension(100, 50));
        elec4.setMinimumSize(new java.awt.Dimension(100, 50));
        elec4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elec4ActionPerformed(evt);
            }
        });
        jPanel5.add(elec4);
        elec4.setBounds(150, 70, 40, 30);

        ps1.setEnabled(false);
        ps1.setMaximumSize(new java.awt.Dimension(100, 50));
        ps1.setMinimumSize(new java.awt.Dimension(100, 50));
        ps1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps1ActionPerformed(evt);
            }
        });
        jPanel5.add(ps1);
        ps1.setBounds(150, 160, 40, 30);

        it207.setEnabled(false);
        it207.setMaximumSize(new java.awt.Dimension(100, 50));
        it207.setMinimumSize(new java.awt.Dimension(100, 50));
        it207.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                it207ActionPerformed(evt);
            }
        });
        jPanel5.add(it207);
        it207.setBounds(150, 130, 40, 30);

        ps2.setEnabled(false);
        ps2.setMaximumSize(new java.awt.Dimension(100, 50));
        ps2.setMinimumSize(new java.awt.Dimension(100, 50));
        ps2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ps2ActionPerformed(evt);
            }
        });
        jPanel5.add(ps2);
        ps2.setBounds(400, 100, 40, 30);

        it206.setEnabled(false);
        it206.setMaximumSize(new java.awt.Dimension(100, 50));
        it206.setMinimumSize(new java.awt.Dimension(100, 50));
        it206.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                it206ActionPerformed(evt);
            }
        });
        jPanel5.add(it206);
        it206.setBounds(400, 70, 40, 30);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 540, 220));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, 30, 50));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 210, 30));

        jScrollPane2.setViewportView(jPanel1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 140, 680, 570);

        jLabel11.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel11.setText("Email:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 370, 100, 23);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 31)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("STUDENT INFORMATION ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 20, 360, 40);

        jLabel17.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setText("(4TH YR. 1st-2nd Sem)");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(180, 50, 230, 40);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("New");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Edit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("Student Info");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        sn.setEnabled(false);
        ln.setEnabled(true);
        fn.setEnabled(true);
        mi.setEnabled(true);
        age.setEnabled(true);
        password.setEnabled(true);
        email.setEnabled(false);
        elec4.setEnabled(true);
        free3.setEnabled(true);
        it207.setEnabled(true);
        ps1.setEnabled(true);
        it206.setEnabled(true);
        ps2.setEnabled(true);
        
        sn.setText("");
        ln.setText("");
        fn.setText("");
        mi.setText("");
        age.setText("");
        password.setText("");
        email.setText("");
        elec4.setText("");
        free3.setText("");
        it207.setText("");
        ps1.setText("");
        it206.setText("");
        ps2.setText("");
        
        SaveButton.setEnabled(true);
        UpdateButton.setEnabled(false);
        jButton3.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
try{
   
      String sql = "insert into studentinfo (LastName,FirstName,MI,Age,Password, Email, Elec4, Free3, IT207, PS1, IT206, PS2)values(?,?,?,?,?,?,?,?,?,?,?,?)";
      pst=conn.prepareStatement(sql);

     // pst.setString(1, sn.getText());
      pst.setString(1, ln.getText());
      pst.setString(2, fn.getText());
      pst.setString(3, mi.getText());
      pst.setString(4, age.getText());
      pst.setString(5, password.getText());
       pst.setString(6, email.getText());
      pst.setString(7, elec4.getText());
      pst.setString(8, free3.getText());
      pst.setString(9, it207.getText());
      pst.setString(10, ps1.getText());
      pst.setString(11, it206.getText());
      pst.setString(12, ps2.getText());
      
      
      
      pst.execute();
     // sn.setText("");
        ln.setText("");
        fn.setText("");
        mi.setText("");
        age.setText("");
        password.setText("");
         email.setText("");
        elec4.setText("");
        free3.setText("");
        it207.setText("");
        ps1.setText("");
        it206.setText("");
        ps2.setText("");
        
        sn.setEnabled(false);
        ln.setEnabled(false);
        fn.setEnabled(false);
        mi.setEnabled(false);
        age.setEnabled(false);
        password.setEnabled(false);
        email.setEnabled(false);
        elec4.setEnabled(false);
        free3.setEnabled(false);
        it207.setEnabled(false);
        ps1.setEnabled(false);
        it206.setEnabled(false);
        ps2.setEnabled(false);
        
      UpdateButton.setEnabled(false);
        jButton3.setEnabled(false);
        select = false;
      JOptionPane.showMessageDialog(null, "Saved");
      Update_Table_StudentInfo();
      
        Email email = new SimpleEmail();
        email.setHostName("smtp.mail.yahoo.com");
        email.setSmtpPort(465);
        email.setAuthenticator(new DefaultAuthenticator("testing_account7@yahoo.com", "dummyaccount1234567"));
        email.setSSLOnConnect(true);
    try {
        email.setFrom("user@gmail.com");email.setSubject("TestMail");
        email.setMsg("This is a test mail ... :-)");
        email.addTo("ivanortiz.miyens@gmail.com");
        email.send();
    } catch (EmailException ex) {
        Logger.getLogger(StudentInformation.class.getName()).log(Level.SEVERE, null, ex);
    }
        
 
      
      }catch(SQLException | HeadlessException e){
      JOptionPane.showMessageDialog(null, e);
      }

      
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
 try{
      int row = stud_info.getSelectedRow();
         String TableClick=(stud_info.getModel().getValueAt(row, 0).toString()); 
     
       String value1 = sn.getText();
       String value2 = ln.getText();
       String value3 = fn.getText();
       String value4 = mi.getText();
       String value5 = age.getText();
       String value6 = password.getText();
       String value7 = email.getText();
       String value8 = elec4.getText();
       String value9 = free3.getText();
       String value10 = it207.getText();
       String value11 = ps1.getText();
       String value12 = it206.getText();
       String value13 = ps2.getText();
             

       String sql="update studentinfo set StudentNumber='"+value1+"',LastName='"+value2+"',FirstName='"+value3+"',MI='"+value4+"',Age='"+value5+"', Password='"+value6+"', Email='"+value7+"', Elec4='"+value8+"', Free3='"+value9+"', IT207='"+value10+"', PS1='"+value11+"', IT206='"+value12+"', PS2='"+value13+"'  where StudentNumber='"+TableClick+"'";
       pst=conn.prepareStatement(sql);
       pst.execute();
       JOptionPane.showMessageDialog(null, "Updated");
       Update_Table_StudentInfo();
            sn.setText("");
        ln.setText("");
        fn.setText("");
        mi.setText("");
        age.setText("");
        password.setText("");
         email.setText("");
        elec4.setText("");
        free3.setText("");
        it207.setText("");
        ps1.setText("");
        it206.setText("");
        ps2.setText("");
        
        sn.setEnabled(false);
        ln.setEnabled(false);
        fn.setEnabled(false);
        mi.setEnabled(false);
        age.setEnabled(false);
        password.setEnabled(false);
         email.setEnabled(false);
        elec4.setEnabled(false);
        free3.setEnabled(false);
        it207.setEnabled(false);
        ps1.setEnabled(false);
        it206.setEnabled(false);
        ps2.setEnabled(false);
        
        UpdateButton.setEnabled(false);
        jButton3.setEnabled(false);
        select = false;
        
        Email email = new SimpleEmail();
        email.setHostName("smtp.mail.yahoo.com");
        email.setSmtpPort(465);
        email.setAuthenticator(new DefaultAuthenticator("testing_account7@yahoo.com", "dummyaccount1234567"));
        email.setSSLOnConnect(true);
    try {
        email.setFrom("user@gmail.com");email.setSubject("TestMail");
        email.setMsg("This is a test mail ... :-)");
        email.addTo("testinga047@gmail.com");
        email.send();
    } catch (EmailException ex) {
        Logger.getLogger(StudentInformation.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
        
       }catch(SQLException | HeadlessException e){
       JOptionPane.showMessageDialog(null, e);

}        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateButtonActionPerformed
    
    private void stud_infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stud_infoMouseClicked
    try{
        
        int row = stud_info.getSelectedRow();
        String Table_click=(stud_info.getModel().getValueAt(row, 0).toString());
        String sql ="select * from studentinfo where StudentNumber='"+Table_click+"'";
        pst=conn.prepareStatement(sql);
          rs=pst.executeQuery();
  if(rs.next()){
  String add1=rs.getString("StudentNumber");
  sn.setText(add1);
  String add2=rs.getString("LastName");
  ln.setText(add2);
  String add3=rs.getString("FirstName");
  fn.setText(add3);
  String add4=rs.getString("MI");
  mi.setText(add4);
  String add5=rs.getString("Age");
  age.setText(add5);
   String add6=rs.getString("Password");
  password.setText(add6);
   String add7=rs.getString("Email");
  email.setText(add7);
   String add8=rs.getString("Elec4");
  elec4.setText(add8);
   String add9=rs.getString("Free3");
  free3.setText(add9);
   String add10=rs.getString("It207");
  it207.setText(add10);
   String add11=rs.getString("PS1");
  ps1.setText(add11);
   String add12=rs.getString("It206");
  it206.setText(add12);
   String add13=rs.getString("Ps2");
  ps2.setText(add13);

        sn.setEnabled(false);
        ln.setEnabled(false);
        fn.setEnabled(false);
        mi.setEnabled(false);
        age.setEnabled(false);
        password.setEnabled(false);
        email.setEnabled(false);
        elec4.setEnabled(false);
        free3.setEnabled(false);
        it207.setEnabled(false);
        ps1.setEnabled(false);
        it206.setEnabled(false);
        ps2.setEnabled(false);
        
        
        jButton3.setEnabled(true);
        select = true;
        stdntnmbr = Integer.parseInt(add1);
  }

        }catch(SQLException | NumberFormatException e){
        JOptionPane.showMessageDialog(null, e);


        }
        // TODO add your handling code here:
    }//GEN-LAST:event_stud_infoMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       if (select)
       {
        sn.setEnabled(false);
        ln.setEnabled(true);
        fn.setEnabled(true);
        mi.setEnabled(true);
        age.setEnabled(true);
        password.setEnabled(true);
        email.setEnabled(true);
         elec4.setEnabled(true);
        free3.setEnabled(true);
        it207.setEnabled(true);
        ps1.setEnabled(true);
        it206.setEnabled(true);
        ps2.setEnabled(true);
        UpdateButton.setEnabled(true);
       }
       else
       {
           JOptionPane.showMessageDialog(null,"Please select data from the table first.");
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

int p = JOptionPane.showConfirmDialog(null,"do you really want to delete it ?","delete",JOptionPane.YES_NO_OPTION);
 if(p==0){
      
        try{
          int row = stud_info.getSelectedRow();
            String TableClick=(stud_info.getModel().getValueAt(row, 0).toString());   
              String sql = "delete from studentinfo where StudentNumber ='"+TableClick+"' ";
        pst=conn.prepareStatement(sql);
       // pst.setString(1, sn.getText());
        pst.execute();
        JOptionPane.showMessageDialog(null,"DELETED");
        sn.setText("");
        ln.setText("");
        fn.setText("");
        mi.setText("");
        age.setText("");
        password.setText("");
        sn.setEnabled(false);
        ln.setEnabled(false);
        fn.setEnabled(false);
        mi.setEnabled(false);
        age.setEnabled(false);
        password.setEnabled(false);
        UpdateButton.setEnabled(false);
        jButton3.setEnabled(false);
        select = false;
        }catch(SQLException | HeadlessException e){
        JOptionPane.showMessageDialog(null, e);



        }
        Update_Table_StudentInfo();
 }       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    // TODO add your handling code here:
        /* Create Connection objects */
        try{
            
                Class.forName ("com.mysql.jdbc.Driver");             
            /* Define the SQL query */
            try (Connection reportconn = DriverManager.getConnection("jdbc:mysql://localhost:3306/accounts","root","");
                    Statement stmt = reportconn.createStatement(); /* Define the SQL query */
                    ResultSet query_set = stmt.executeQuery("select * from studentinfo where StudentNumber='"+stdntnmbr+"'")) {
                /* Step-2: Initialize PDF documents - logical objects */
                Document my_pdf_report = new Document();
                PdfWriter.getInstance(my_pdf_report, new FileOutputStream("Pdf_Report.pdf"));
                my_pdf_report.open();            
                //we have four columns in our table
                PdfPTable my_report_table = new PdfPTable(5);
                //create a cell object
                PdfPCell table_cell;
                
                while (query_set.next()) {
                    String student_number = query_set.getString("StudentNumber");
                    table_cell=new PdfPCell(new Phrase(student_number));
                    my_report_table.addCell(table_cell);
                    
                    String LastName=query_set.getString("LastName");
                    table_cell=new PdfPCell(new Phrase(LastName));
                    my_report_table.addCell(table_cell);
                    
                    String FirstName=query_set.getString("FirstName");
                    table_cell=new PdfPCell(new Phrase(FirstName));
                    my_report_table.addCell(table_cell);
                    
                    String MI=query_set.getString("MI");
                    table_cell=new PdfPCell(new Phrase(MI));
                    my_report_table.addCell(table_cell);
                    
                    String Age=query_set.getString("Age");
                    table_cell=new PdfPCell(new Phrase(Age));
                    my_report_table.addCell(table_cell);
                    
                       String Email=query_set.getString("Email");
                    table_cell=new PdfPCell(new Phrase(Email));
                    my_report_table.addCell(table_cell);
                }
                /* Attach report table to PDF */
                my_pdf_report.add(my_report_table);                       
                my_pdf_report.close();
            if(Desktop.isDesktopSupported())
            {
                try{
                    File pdfreport = new File("Pdf_Report.pdf");
                    Desktop.getDesktop().open(pdfreport);
                }
                catch(IOException ex)
                {
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
            } 
        }
        catch(ClassNotFoundException | SQLException | FileNotFoundException | DocumentException e){
        JOptionPane.showMessageDialog(null, e);
        }
    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        String query =jTextField1.getText().toLowerCase();
        filter(query);
    }//GEN-LAST:event_jTextField1KeyReleased

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void free3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_free3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_free3ActionPerformed

    private void elec4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elec4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elec4ActionPerformed

    private void ps1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ps1ActionPerformed

    private void it207ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_it207ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_it207ActionPerformed

    private void ps2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ps2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ps2ActionPerformed

    private void it206ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_it206ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_it206ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new StudentInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField age;
    private javax.swing.JTextField elec4;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fn;
    private javax.swing.JTextField free3;
    private javax.swing.JTextField it206;
    private javax.swing.JTextField it207;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField ln;
    private javax.swing.JTextField mi;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField ps1;
    private javax.swing.JTextField ps2;
    private javax.swing.JTextField sn;
    private javax.swing.JTable stud_info;
    // End of variables declaration//GEN-END:variables
}
